language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-android-support
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle